"""Custom spaCy EntityRuler for ISRO-specific terminology."""

ISRO_PATTERNS = [
    # ── Missions ──────────────────────────────────────────────────
    {"label": "MISSION", "pattern": "Chandrayaan-1"},
    {"label": "MISSION", "pattern": "Chandrayaan-2"},
    {"label": "MISSION", "pattern": "Chandrayaan-3"},
    {"label": "MISSION", "pattern": "Chandrayaan"},
    {"label": "MISSION", "pattern": "Mangalyaan"},
    {"label": "MISSION", "pattern": "Mars Orbiter Mission"},
    {"label": "MISSION", "pattern": "MOM"},
    {"label": "MISSION", "pattern": "Aditya-L1"},
    {"label": "MISSION", "pattern": "Aditya L1"},
    {"label": "MISSION", "pattern": "Gaganyaan"},
    {"label": "MISSION", "pattern": "AstroSat"},
    {"label": "MISSION", "pattern": "Astrosat"},
    {"label": "MISSION", "pattern": "SpaDeX"},
    {"label": "MISSION", "pattern": "SPADEX"},
    {"label": "MISSION", "pattern": "Shukrayaan"},
    {"label": "MISSION", "pattern": "Shukrayaan-1"},
    {"label": "MISSION", "pattern": "NISAR"},
    {"label": "MISSION", "pattern": "XPoSat"},
    {"label": "MISSION", "pattern": "RESOURCESAT"},
    {"label": "MISSION", "pattern": "CARTOSAT"},
    {"label": "MISSION", "pattern": "Cartosat"},
    {"label": "MISSION", "pattern": "EMISAT"},
    {"label": "MISSION", "pattern": "RISAT"},
    {"label": "MISSION", "pattern": "OCEANSAT"},
    {"label": "MISSION", "pattern": "Oceansat"},
    {"label": "MISSION", "pattern": "EDUSAT"},
    {"label": "MISSION", "pattern": "GSAT"},
    {"label": "MISSION", "pattern": "INSAT"},
    {"label": "MISSION", "pattern": "Aryabhata"},
    {"label": "MISSION", "pattern": "Rohini"},
    {"label": "MISSION", "pattern": "APPLE"},
    {"label": "MISSION", "pattern": "IRS-1A"},
    {"label": "MISSION", "pattern": "IRS-1B"},
    {"label": "MISSION", "pattern": "IRS-1C"},
    {"label": "MISSION", "pattern": "IRS-1D"},
    {"label": "MISSION", "pattern": "IRS-P6"},
    {"label": "MISSION", "pattern": "SARAL"},
    {"label": "MISSION", "pattern": "Megha-Tropiques"},

    # ── Launch Vehicles ───────────────────────────────────────────
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV Mk III"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV MkIII"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV Mk-III"},
    {"label": "LAUNCH_VEHICLE", "pattern": "LVM3"},
    {"label": "LAUNCH_VEHICLE", "pattern": "LVM-3"},
    {"label": "LAUNCH_VEHICLE", "pattern": "SSLV"},
    {"label": "LAUNCH_VEHICLE", "pattern": "SLV"},
    {"label": "LAUNCH_VEHICLE", "pattern": "SLV-3"},
    {"label": "LAUNCH_VEHICLE", "pattern": "ASLV"},
    {"label": "LAUNCH_VEHICLE", "pattern": "RLV"},
    {"label": "LAUNCH_VEHICLE", "pattern": "RLV-TD"},
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV-C37"},
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV-C11"},
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV-C25"},
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV-C57"},
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV-C60"},
    {"label": "LAUNCH_VEHICLE", "pattern": "PSLV-XL"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV-D5"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV-D2"},
    {"label": "LAUNCH_VEHICLE", "pattern": "GSLV-F10"},
    {"label": "LAUNCH_VEHICLE", "pattern": "LVM3-M2"},
    {"label": "LAUNCH_VEHICLE", "pattern": "LVM3-M4"},

    # ── Payloads and Instruments ──────────────────────────────────
    {"label": "PAYLOAD", "pattern": "VELC"},
    {"label": "PAYLOAD", "pattern": "SUIT"},
    {"label": "PAYLOAD", "pattern": "ASPEX"},
    {"label": "PAYLOAD", "pattern": "PAPA"},
    {"label": "PAYLOAD", "pattern": "SoLEXS"},
    {"label": "PAYLOAD", "pattern": "HEL1OS"},
    {"label": "PAYLOAD", "pattern": "STEPS"},
    {"label": "PAYLOAD", "pattern": "CHACE"},
    {"label": "PAYLOAD", "pattern": "CHACE-2"},
    {"label": "PAYLOAD", "pattern": "OHRC"},
    {"label": "PAYLOAD", "pattern": "IIRS"},
    {"label": "PAYLOAD", "pattern": "TMC"},
    {"label": "PAYLOAD", "pattern": "TMC-2"},
    {"label": "PAYLOAD", "pattern": "LIBS"},
    {"label": "PAYLOAD", "pattern": "APXS"},
    {"label": "PAYLOAD", "pattern": "ILSA"},
    {"label": "PAYLOAD", "pattern": "SHAPE"},
    {"label": "PAYLOAD", "pattern": "Moon Impact Probe"},
    {"label": "PAYLOAD", "pattern": "MIP"},
    {"label": "PAYLOAD", "pattern": "Mini SAR"},
    {"label": "PAYLOAD", "pattern": "HySI"},
    {"label": "PAYLOAD", "pattern": "LACE"},
    {"label": "PAYLOAD", "pattern": "SIR-2"},
    {"label": "PAYLOAD", "pattern": "NavCam"},
    {"label": "PAYLOAD", "pattern": "PRAGYAN"},
    {"label": "PAYLOAD", "pattern": "Pragyan"},
    {"label": "PAYLOAD", "pattern": "VIKRAM"},
    {"label": "PAYLOAD", "pattern": "Vikram"},
    {"label": "PAYLOAD", "pattern": "SAR"},

    # ── ISRO Centres and Organisations ───────────────────────────
    {"label": "ORG", "pattern": "ISRO"},
    {"label": "ORG", "pattern": "VSSC"},
    {"label": "ORG", "pattern": "URSC"},
    {"label": "ORG", "pattern": "SAC"},
    {"label": "ORG", "pattern": "NRSC"},
    {"label": "ORG", "pattern": "ISTRAC"},
    {"label": "ORG", "pattern": "LPSC"},
    {"label": "ORG", "pattern": "SDSC"},
    {"label": "ORG", "pattern": "SDSC SHAR"},
    {"label": "ORG", "pattern": "ISITE"},
    {"label": "ORG", "pattern": "NARL"},
    {"label": "ORG", "pattern": "SAC"},
    {"label": "ORG", "pattern": "DECU"},
    {"label": "ORG", "pattern": "DOS"},
    {"label": "ORG", "pattern": "NewSpace India Limited"},
    {"label": "ORG", "pattern": "NSIL"},
    {"label": "ORG", "pattern": "Antrix"},
    {"label": "ORG", "pattern": "IN-SPACe"},

    # ── Scientists and Chairmen ───────────────────────────────────
    {"label": "PERSON", "pattern": "Vikram Sarabhai"},
    {"label": "PERSON", "pattern": "Satish Dhawan"},
    {"label": "PERSON", "pattern": "U R Rao"},
    {"label": "PERSON", "pattern": "UR Rao"},
    {"label": "PERSON", "pattern": "K Kasturirangan"},
    {"label": "PERSON", "pattern": "Kasturirangan"},
    {"label": "PERSON", "pattern": "G Madhavan Nair"},
    {"label": "PERSON", "pattern": "Madhavan Nair"},
    {"label": "PERSON", "pattern": "K Radhakrishnan"},
    {"label": "PERSON", "pattern": "Radhakrishnan"},
    {"label": "PERSON", "pattern": "A S Kiran Kumar"},
    {"label": "PERSON", "pattern": "Kiran Kumar"},
    {"label": "PERSON", "pattern": "K Sivan"},
    {"label": "PERSON", "pattern": "K. Sivan"},
    {"label": "PERSON", "pattern": "S Somanath"},
    {"label": "PERSON", "pattern": "S. Somanath"},
    {"label": "PERSON", "pattern": "Somanath"},
    {"label": "PERSON", "pattern": "V Narayanan"},
    {"label": "PERSON", "pattern": "V. Narayanan"},
    {"label": "PERSON", "pattern": "Narayanan"},
    {"label": "PERSON", "pattern": "M Annadurai"},
    {"label": "PERSON", "pattern": "Annadurai"},
    {"label": "PERSON", "pattern": "Nambi Narayanan"},
    {"label": "PERSON", "pattern": "P S Goel"},
    {"label": "PERSON", "pattern": "Mylswamy Annadurai"},

    # ── Navigation and Applications ───────────────────────────────
    {"label": "MISSION", "pattern": "NavIC"},
    {"label": "MISSION", "pattern": "IRNSS"},
    {"label": "MISSION", "pattern": "GAGAN"},
    {"label": "MISSION", "pattern": "IRNSS-1A"},
    {"label": "MISSION", "pattern": "IRNSS-1B"},
    {"label": "MISSION", "pattern": "IRNSS-1C"},
    {"label": "MISSION", "pattern": "IRNSS-1D"},
    {"label": "MISSION", "pattern": "IRNSS-1E"},
    {"label": "MISSION", "pattern": "IRNSS-1F"},
    {"label": "MISSION", "pattern": "IRNSS-1G"},
    {"label": "MISSION", "pattern": "IRNSS-1I"},

    # ── Communication Satellites ──────────────────────────────────
    {"label": "MISSION", "pattern": "GSAT-11"},
    {"label": "MISSION", "pattern": "GSAT-29"},
    {"label": "MISSION", "pattern": "GSAT-19"},
    {"label": "MISSION", "pattern": "GSAT-20"},
    {"label": "MISSION", "pattern": "INSAT-4A"},
    {"label": "MISSION", "pattern": "INSAT-4B"},
    {"label": "MISSION", "pattern": "CMS-01"},
    {"label": "MISSION", "pattern": "CMS-02"},

    # ── Key Locations ─────────────────────────────────────────────
    {"label": "LOC", "pattern": "Sriharikota"},
    {"label": "LOC", "pattern": "Thumba"},
    {"label": "LOC", "pattern": "Thiruvananthapuram"},
    {"label": "LOC", "pattern": "Bengaluru"},
    {"label": "LOC", "pattern": "Ahmedabad"},
    {"label": "LOC", "pattern": "Hyderabad"},
    {"label": "LOC", "pattern": "Hassan"},
    {"label": "LOC", "pattern": "Mahendragiri"},

    # ── Technologies ──────────────────────────────────────────────
    {"label": "TECH", "pattern": "CE-7.5"},
    {"label": "TECH", "pattern": "SCE-200"},
    {"label": "TECH", "pattern": "Vikas engine"},
    {"label": "TECH", "pattern": "Vikas"},
    {"label": "TECH", "pattern": "HTPB"},
    {"label": "TECH", "pattern": "cryogenic engine"},
    {"label": "TECH", "pattern": "Bharatiya Docking System"},
    {"label": "TECH", "pattern": "BDS"},
    {"label": "TECH", "pattern": "Crew Escape System"},
    {"label": "TECH", "pattern": "CES"},
    {"label": "TECH", "pattern": "Liquid Apogee Motor"},
    {"label": "TECH", "pattern": "LAM"},
    {"label": "TECH", "pattern": "Terrain Mapping Camera"},
    {"label": "TECH", "pattern": "Hall thruster"},
]


def add_entity_ruler(nlp):
    """Add ISRO entity ruler to a spaCy pipeline."""
    if "entity_ruler" not in nlp.pipe_names:
        ruler = nlp.add_pipe("entity_ruler", before="ner")
    else:
        ruler = nlp.get_pipe("entity_ruler")
    ruler.add_patterns(ISRO_PATTERNS)
    return nlp